export const OBJECTIVE_QUESTIONS_PER_EXERCISE = 7;
export const SUBJECTIVE_QUESTIONS_PER_EXERCISE = 3;
export const QUESTIONS_PER_EXERCISE = OBJECTIVE_QUESTIONS_PER_EXERCISE + SUBJECTIVE_QUESTIONS_PER_EXERCISE;
