/* Original diagrams and lesson cards; textbook page images are never reproduced. */
const fs = require('fs');
const path = require('path');
const { createCanvas, GlobalFonts } = require(process.env.CANVAS_MODULE || '@napi-rs/canvas');

const slug = process.argv[2];
if (!slug) throw new Error('Usage: node render.cjs lesson-slug');
const ROOT = path.resolve(__dirname, '../..');
const WORK = process.env.LESSON_WORK || `/private/tmp/${slug}-production`;
const OUT = path.join(ROOT, 'output/video', slug);
const DATA = JSON.parse(fs.readFileSync(path.join(WORK, 'timeline.json'), 'utf8'));
const FRAMES = path.join(WORK, 'frames');
const W = 1600, H = 900;
const C = { bg:'#F4F0E6', white:'#FFFEFA', ink:'#173441', muted:'#56707A', navy:'#183B51', teal:'#13737A', turquoise:'#D9EEEC', gold:'#E8B955', amber:'#FFF0CD', coral:'#D77A61', blush:'#F8E4DF', line:'#C9D8D5', blue:'#69AFCA', green:'#73A98D', sand:'#E7D6B5' };
const FONT_DIR = process.env.LESSON_FONT_DIR || '/System/Library/Fonts/Supplemental';
GlobalFonts.registerFromPath(path.join(FONT_DIR, 'Arial.ttf'), 'Tutor');
GlobalFonts.registerFromPath(path.join(FONT_DIR, 'Arial Bold.ttf'), 'TutorBold');
GlobalFonts.registerFromPath(path.join(FONT_DIR, 'Georgia.ttf'), 'Story');

function rect(c,x,y,w,h,r,fill,stroke,width=2){c.beginPath();c.roundRect(x,y,w,h,r);if(fill){c.fillStyle=fill;c.fill()}if(stroke){c.strokeStyle=stroke;c.lineWidth=width;c.stroke()}}
function line(c,x1,y1,x2,y2,color=C.line,width=3){c.beginPath();c.moveTo(x1,y1);c.lineTo(x2,y2);c.strokeStyle=color;c.lineWidth=width;c.lineCap='round';c.stroke()}
function arrow(c,x1,y1,x2,y2,color=C.coral,width=5){line(c,x1,y1,x2,y2,color,width);const a=Math.atan2(y2-y1,x2-x1);c.beginPath();c.moveTo(x2,y2);c.lineTo(x2-15*Math.cos(a-.55),y2-15*Math.sin(a-.55));c.lineTo(x2-15*Math.cos(a+.55),y2-15*Math.sin(a+.55));c.closePath();c.fillStyle=color;c.fill()}
function text(c,s,x,y,size=28,color=C.ink,font='Tutor',align='left'){c.font=`${size}px ${font}`;c.textAlign=align;c.textBaseline='alphabetic';c.fillStyle=color;c.fillText(s,x,y)}
function wrap(c,s,max,size,font='Tutor'){c.font=`${size}px ${font}`;const rows=[];for(const p of String(s).split('\n')){let row='';for(const word of p.split(/\s+/)){const next=row?row+' '+word:word;if(c.measureText(next).width>max&&row){rows.push(row);row=word}else row=next}if(row)rows.push(row)}return rows}
function block(c,s,x,y,w,size=27,leading=36,color=C.ink,font='Tutor',maxRows=7){const rows=wrap(c,s,w,size,font);if(rows.length>maxRows)throw new Error(`Overflow: ${s}`);rows.forEach((row,i)=>text(c,row,x,y+i*leading,size,color,font));return rows.length*leading}
function pill(c,label,x,y,fill=C.teal,fg=C.white,size=19){c.font=`${size}px TutorBold`;const w=c.measureText(label).width+30;rect(c,x,y,w,36,17,fill);text(c,label,x+15,y+25,size,fg,'TutorBold');return w}
function card(c,x,y,w,h,label,body,fill=C.white,accent=C.teal){rect(c,x,y,w,h,18,fill,C.line);rect(c,x,y,9,h,[18,0,0,18],accent);block(c,label,x+25,y+39,w-45,24,29,accent,'TutorBold',2);block(c,body,x+25,y+82,w-47,22,29,C.ink,'Tutor',3)}

function header(c,scene,index){rect(c,0,0,W,110,0,C.white);rect(c,58,30,59,54,16,C.teal);text(c,String(index+1).padStart(2,'0'),87,67,24,C.white,'TutorBold','center');const title=DATA.title.toUpperCase();let size=31;while(c.measureText(title).width>850&&size>24){size--;c.font=`${size}px TutorBold`}text(c,title,137,67,size,C.navy,'TutorBold');text(c,scene.title,1542,68,25,C.muted,'Story','right');line(c,60,109,1541,109,C.line,2)}
function left(c,scene,ev){rect(c,58,137,551,558,24,C.white,C.line);pill(c,ev.kind==='ask'||ev.kind==='think'?'YOUR TURN':ev.kind==='reveal'?'CHECK':'NOTICE',86,165,ev.kind==='think'?C.gold:C.teal,ev.kind==='think'?C.ink:C.white,20);
  if(ev.kind==='ask'||ev.kind==='think'){block(c,scene.question,88,271,484,38,51,C.navy,'Story',7);if(ev.kind==='think'){rect(c,88,492,489,110,18,C.amber);text(c,'Think. Say your answer.',113,546,27,C.ink,'TutorBold');text(c,String(ev.count),548,578,50,C.teal,'TutorBold','right')}else text(c,'Pause longer if you need to.',88,633,24,C.muted);return}
  if(ev.kind==='reveal'){block(c,scene.answer,88,273,484,37,49,C.navy,'Story',7);text(c,'Explain it in your own words.',88,632,23,C.muted);return}
  text(c,'Build the picture',88,245,33,C.navy,'Story');scene.items.slice(0,3).forEach(([label,body],i)=>{const active=ev.beat===i;const y=277+i*119;rect(c,87,y,488,98,17,active?C.turquoise:C.bg,active?C.teal:C.line,active?3:1);rect(c,106,y+23,44,44,22,active?C.teal:C.line);text(c,String(i+1),128,y+53,23,active?C.white:C.ink,'TutorBold','center');block(c,label,169,y+38,386,22,27,active?C.navy:C.muted,'TutorBold',1);block(c,body,169,y+70,385,20,25,C.muted,'Tutor',1)});text(c,'Class 6 History · revision from the source pages',89,654,20,C.muted)}
function base(c,label){rect(c,639,137,902,558,24,C.white,C.line);pill(c,label,669,165,C.navy,C.white,19)}
function three(c,scene,mode){base(c,mode);const items=scene.items;if(items.length===4){items.forEach(([a,b],i)=>{const x=670+(i%2)*423,y=245+Math.floor(i/2)*197;card(c,x,y,393,165,a,b,[C.turquoise,C.amber,C.blush,C.bg][i],[C.teal,C.navy,C.coral,C.teal][i])});return}
  if(scene.layout==='flow'||scene.layout==='sources'||scene.layout==='afterlife'){items.forEach(([a,b],i)=>{const x=670+i*286;card(c,x,319,262,214,a,b,[C.turquoise,C.amber,C.blush][i],[C.teal,C.navy,C.coral][i]);if(i<2)arrow(c,x+263,426,x+282,426)});text(c,mode==='EVIDENCE'?'Different sources reveal different clues.':'Connect each step to the next.',1090,616,24,C.muted,'Story','center');return}
  if(scene.layout==='timeline'){line(c,718,425,1468,425,C.line,8);items.forEach(([a,b],i)=>{const x=682+i*283;rect(c,x,304,250,90,17,[C.turquoise,C.amber,C.blush][i],C.line);text(c,a,x+125,343,25,C.navy,'TutorBold','center');text(c,b,x+125,377,21,C.muted,'Tutor','center');rect(c,x+111,408,28,28,14,C.teal)});text(c,'Old → Middle → New Kingdom',1090,539,30,C.navy,'TutorBold','center');text(c,'Dates are approximate.',1090,586,23,C.muted,'Story','center');return}
  if(scene.layout==='society'){const widths=[340,520,700];items.forEach(([a,b],i)=>{const x=1090-widths[i]/2,y=266+i*115;rect(c,x,y,widths[i],95,16,[C.amber,C.turquoise,C.bg][i],C.line);text(c,a,x+23,y+38,23,C.teal,'TutorBold');text(c,b,x+23,y+72,22,C.ink)});text(c,'A broad textbook outline · lives varied',1090,650,23,C.muted,'Story','center');return}
  if(scene.layout==='nile'){rect(c,679,255,294,339,22,C.sand);c.beginPath();c.moveTo(805,588);c.bezierCurveTo(900,526,747,450,842,369);c.bezierCurveTo(918,304,799,300,852,262);c.strokeStyle=C.blue;c.lineWidth=46;c.stroke();text(c,'NILE',825,629,28,C.navy,'TutorBold','center');items.forEach(([a,b],i)=>card(c,1010,248+i*129,492,111,a,b,[C.turquoise,C.amber,C.bg][i],[C.teal,C.navy,C.coral][i]));return}
  if(scene.layout==='buildings'){c.beginPath();c.moveTo(700,594);c.lineTo(858,270);c.lineTo(1016,594);c.closePath();c.fillStyle=C.sand;c.fill();line(c,700,594,1016,594,C.coral,5);text(c,'PYRAMID',858,632,22,C.muted,'TutorBold','center');items.forEach(([a,b],i)=>card(c,1050,247+i*127,445,108,a,b,[C.turquoise,C.amber,C.bg][i],[C.teal,C.navy,C.coral][i]));return}
  items.forEach(([a,b],i)=>{const x=670+i*286;card(c,x,309,262,220,a,b,[C.turquoise,C.amber,C.blush][i],[C.teal,C.navy,C.coral][i])})}
function diagram(c,scene){const labels={compare:'THEN AND LATER',sources:'EVIDENCE',flow:'CAUSE AND CHANGE',stages:'FOUR STAGES',recap:'REBUILD FROM MEMORY',nile:'RIVER AND DESERT',timeline:'THREE KINGDOMS',buildings:'PLACES PEOPLE BUILT',society:'SOCIAL GROUPS',afterlife:'BELIEF AND PRACTICE'};three(c,scene,labels[scene.layout]||'KEY IDEAS')}
function caption(c,ev){rect(c,58,713,1483,147,22,C.navy);const msg=ev.kind==='think'?'Think, then say your answer aloud. Pause if you need more time.':ev.kind==='gap'?'':ev.text;if(!msg)return;let size=30,rows=wrap(c,msg,1375,size,'Tutor');while(rows.length>3&&size>23){size-=1;rows=wrap(c,msg,1375,size,'Tutor')}if(rows.length>3)throw new Error(`Caption overflow: ${msg}`);const step=size+9,baseline=792-(rows.length-1)*step/2;rows.forEach((row,i)=>text(c,row,800,baseline+i*step,size,C.white,'Tutor','center'))}
function frame(ev,scene,index){const canvas=createCanvas(W,H),c=canvas.getContext('2d');c.fillStyle=C.bg;c.fillRect(0,0,W,H);header(c,scene,index);left(c,scene,ev);diagram(c,scene);caption(c,ev);c.fillStyle=C.gold;c.fillRect(58,884,1483*Math.min(1,ev.start/DATA.duration),6);return canvas.toBuffer('image/png')}
function main(){fs.mkdirSync(FRAMES,{recursive:true});fs.mkdirSync(OUT,{recursive:true});const lines=['ffconcat version 1.0'],manifest=[];let last=null;for(let i=0;i<DATA.events.length;i++){const ev=DATA.events[i],scene=DATA.scenes[ev.scene];let file;if(ev.kind==='gap'&&last){file=last}else{file=path.join(FRAMES,`frame-${String(i).padStart(4,'0')}.png`);fs.writeFileSync(file,frame(ev,scene,ev.scene));last=file}lines.push(`file '${file.replaceAll("'","'\\''")}'`,`duration ${(ev.end-ev.start).toFixed(6)}`);manifest.push({index:i,scene:ev.scene,kind:ev.kind,file,duration:ev.end-ev.start})}lines.push(`file '${last}'`);fs.writeFileSync(path.join(WORK,'frames.ffconcat'),lines.join('\n')+'\n');fs.writeFileSync(path.join(WORK,'frame-manifest.json'),JSON.stringify(manifest,null,2));fs.copyFileSync(path.join(FRAMES,'frame-0000.png'),path.join(OUT,'poster.png'));console.log(JSON.stringify({slug,events:DATA.events.length,frames:fs.readdirSync(FRAMES).length,duration:DATA.duration}))}
main();
